// Generated by CoffeeScript 1.9.3
(function() {
  var Site, WeedProxite, argv, host, misc, port, site;

  WeedProxite = require('WeedProxite');

  Site = WeedProxite.Site;

  misc = WeedProxite.misc;


  /*
   Run as `node main.js localhost 1984`
   */

  if (require.main === module) {
    argv = process.argv;
    host = argv[2];
    port = argv[3];
  }

  host || (host = process.env.host);

  port || (port = process.env.port);

  site = new Site(__dirname);

  if (site.config.showJiathis) {
    site.use({
      host: 'v3.jiathis.com',
      mime: 'text/html',
      before: function(req, res, next) {
        req.localConfig.showJiathis = false;
        req.localConfig.enableAppcache = false;
        return next();
      }
    });
  }

  site.useDefault();

  site.run(host, port);

}).call(this);
