// Generated by CoffeeScript 1.9.0
(function() {
  var Site, WeedProxite, argv, main, misc;

  WeedProxite = require('WeedProxite');

  Site = WeedProxite.Site;

  misc = WeedProxite.misc;

  main = function(host, port) {
    var site;
    site = new Site(__dirname);
    site.use({
      host:'v3.jiathis.com',
      mime:'text/html',
      before:function (req,res,next) {
        //req.localConfig.location.ctrlType='iframe';
        // don't display jiathis in itself
        //req.localConfig.disableJiathis = true;
        req.localConfig.disableRewriteHTML = true;
        next();
      }
    });

    site.use({
      host:'pao-pao.net',
      path:'/vpn-compare',
      after:function (proxyRes,res,next,proxyReq,req) {
        if (!proxyRes.headers['content-type']) {
          proxyRes.headers['content-type']='text/html; charset=utf-8';
        }
        proxyRes.withTextBody(function (err,body) {
          if (err) return next(err);
          var re = /<script\b[^>]*>[^<]*\bvpnjson\b[^]+?<\/script>/i;
          body = body.replace(
            re,
            function (s) {
              s = s.replace(/\bhttps?:/ig,'\\/$&');
              return s;
            }
          );
          proxyRes.body=body;
          next();
        });
      }
    });

    site.useDefault();
    site.run(host, port);
    return site;
  };

  module.exports = main;

  argv = process.argv;


  /*
   Run as `node site.js localhost 8080`
   */

  if (require.main === module) {
    main(argv[2], argv[3]);
  }

}).call(this);
